name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install PlatformIO
        run: |
          python -m pip install pip wheel --upgrade
          python -m pip install platformio --upgrade

      - name: Install Device Platforms
        run: |
          pio platform install atmelavr teensy

      - name: Run PlatformIO
        run: pio run --environment teensy41 --verbose

  test:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'tests skip')"

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install PlatformIO
        run: |
          python -m pip install pip wheel --upgrade
          python -m pip install platformio --upgrade
      
      - name: Install Device Platforms
        run: |
          pio platform install atmelavr teensy
      
      - name: Add CLI Option to platformio.ini
        run: echo "upload_protocol = teensy-cli" >> platformio.ini

      - name: Test PlatformIO
        run: pio test --verbose