name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install PlatformIO
        run: |
          python -m pip install pip wheel --upgrade
          python -m pip install platformio --upgrade

      - name: Install device platforms
        run: |
          pio platform install atmelavr teensy

      - name: Run PlatformIO
        run: pio run --environment teensy41 --verbose

  test:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'tests skip')"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install PlatformIO and deps
        run: |
          python -m pip install pip wheel --upgrade
          python -m pip install platformio --upgrade
          python -m pip install cryptography --upgrade
      
      - name: Install device platforms
        run: |
          pio platform install atmelavr teensy

      - name: Run remote tests on the embedded target
        env:
          PLATFORMIO_AUTH_TOKEN: ${{ secrets.PLATFORMIO_AUTH_TOKEN }}
        run: pio remote test --environment teensy41 --verbose